# fly.toml app configuration file generated for keyboard-events on 2024-03-28T14:10:55+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'keyboard-events'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
